modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="theevanmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="The Evan Mod" #mandatory
authors="EvanGamer2018 or Evan Goemer" #optional
description='''
The Evan Mod
Adds a bunch of stuff to the game that I would like in it.
'''